"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const electron_1 = require("electron");
const mainPage_1 = require("./ui/mainPage");
const React = require("react");
const ReactDOM = require("react-dom");
let main_win = electron_1.remote.BrowserWindow.getAllWindows()[0];
let element = document.createElement('div');
document.body.appendChild(element);
ReactDOM.render(React.createElement(mainPage_1.MainPage, { win: main_win, mainPath: __dirname }), element);
